/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentUploadRouteImport } from './routes/student.upload'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentAnalysisRouteImport } from './routes/student.analysis'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminDatasetsRouteImport } from './routes/admin.datasets'
import { Route as AdminClustersRouteImport } from './routes/admin.clusters'
import { Route as AdminClusterDetailRouteImport } from './routes/admin.cluster-detail'
import { Route as AdminAnalysisRouteImport } from './routes/admin.analysis'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentUploadRoute = StudentUploadRouteImport.update({
  id: '/student/upload',
  path: '/student/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAnalysisRoute = StudentAnalysisRouteImport.update({
  id: '/student/analysis',
  path: '/student/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/admin/upload',
  path: '/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/admin/results',
  path: '/admin/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDatasetsRoute = AdminDatasetsRouteImport.update({
  id: '/admin/datasets',
  path: '/admin/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersRoute = AdminClustersRouteImport.update({
  id: '/admin/clusters',
  path: '/admin/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClusterDetailRoute = AdminClusterDetailRouteImport.update({
  id: '/admin/cluster-detail',
  path: '/admin/cluster-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalysisRoute = AdminAnalysisRouteImport.update({
  id: '/admin/analysis',
  path: '/admin/analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workflow': typeof WorkflowRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/cluster-detail': typeof AdminClusterDetailRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/student/analysis': typeof StudentAnalysisRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/upload': typeof StudentUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workflow': typeof WorkflowRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/cluster-detail': typeof AdminClusterDetailRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/student/analysis': typeof StudentAnalysisRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/upload': typeof StudentUploadRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workflow': typeof WorkflowRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/cluster-detail': typeof AdminClusterDetailRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/student/analysis': typeof StudentAnalysisRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/upload': typeof StudentUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/workflow'
    | '/admin/analysis'
    | '/admin/cluster-detail'
    | '/admin/clusters'
    | '/admin/datasets'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/upload'
    | '/student/analysis'
    | '/student/profile'
    | '/student/results'
    | '/student/upload'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/workflow'
    | '/admin/analysis'
    | '/admin/cluster-detail'
    | '/admin/clusters'
    | '/admin/datasets'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/upload'
    | '/student/analysis'
    | '/student/profile'
    | '/student/results'
    | '/student/upload'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/workflow'
    | '/admin/analysis'
    | '/admin/cluster-detail'
    | '/admin/clusters'
    | '/admin/datasets'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/upload'
    | '/student/analysis'
    | '/student/profile'
    | '/student/results'
    | '/student/upload'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WorkflowRoute: typeof WorkflowRoute
  AdminAnalysisRoute: typeof AdminAnalysisRoute
  AdminClusterDetailRoute: typeof AdminClusterDetailRoute
  AdminClustersRoute: typeof AdminClustersRoute
  AdminDatasetsRoute: typeof AdminDatasetsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  StudentAnalysisRoute: typeof StudentAnalysisRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentUploadRoute: typeof StudentUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/upload': {
      id: '/student/upload'
      path: '/student/upload'
      fullPath: '/student/upload'
      preLoaderRoute: typeof StudentUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/analysis': {
      id: '/student/analysis'
      path: '/student/analysis'
      fullPath: '/student/analysis'
      preLoaderRoute: typeof StudentAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/admin/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/datasets': {
      id: '/admin/datasets'
      path: '/admin/datasets'
      fullPath: '/admin/datasets'
      preLoaderRoute: typeof AdminDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clusters': {
      id: '/admin/clusters'
      path: '/admin/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AdminClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cluster-detail': {
      id: '/admin/cluster-detail'
      path: '/admin/cluster-detail'
      fullPath: '/admin/cluster-detail'
      preLoaderRoute: typeof AdminClusterDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analysis': {
      id: '/admin/analysis'
      path: '/admin/analysis'
      fullPath: '/admin/analysis'
      preLoaderRoute: typeof AdminAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WorkflowRoute: WorkflowRoute,
  AdminAnalysisRoute: AdminAnalysisRoute,
  AdminClusterDetailRoute: AdminClusterDetailRoute,
  AdminClustersRoute: AdminClustersRoute,
  AdminDatasetsRoute: AdminDatasetsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUploadRoute: AdminUploadRoute,
  StudentAnalysisRoute: StudentAnalysisRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentUploadRoute: StudentUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
